- pkg/api/featureflags.go
- pkg/api/openshiftcluster.go
- pkg/installer/custominstallconfig.go
- pkg/installer/deployresources_resources.go
- pkg/installer/generateconfig.go
- pkg/installer/install.go
Changes:
- gofmt changes:
- ~~Removed func setupFileHook(baseDir string) func() { as it was unused~~
- Removed Context from func (m *manager) applyInstallConfigCustomisations as it was an unused parameter
- changes to acommodate public ip removal
Changes were pulled directly from https://github.com/hawkowl/ARO-Installer/pull/5/.  Additional changes were needed for `pkg/api/openshiftcluster.go` as well.
> Installer changes to accomodate public ip removal

- pkg/util/instancemetadata/prod.go
The resource manager endpoint is dependant on the Cloud Environment, so we need to use the dynamically populated `instanceMetadata.environment.ResourceManagerEndpoint` to ensure we can authenticate in anywhere.
I have tested this by building both a 4.10 and a 4.11 Installer and creating clusters in a dedicated RP environment.
> Use instancemeta populated resource manager endpoint

- Dockerfile.aro
Which issue this PR addresses:
Fixes ARO-Installer go-toolset version
What this PR does / why we need it:
Updating go-toolset version from 1.18.4-8 to 1.18.4. As 1.18.4-8 does not exist on our ACR
Test plan for issue:
N/A
Is there any documentation that needs to be updated for this PR?
N/A
> Updating go-toolset version to 1.18.4 from 1.18.4-8

- pkg/installer/deployresources_resources.go
- pkg/installer/generateconfig.go
- pkg/installer/generateconfig_test.go
**Which issue this PR addresses:**
Fixes https://issues.redhat.com/browse/ARO-1487
**What this PR does / why we need it:**
This PR enables Accelerated Networking for VM Types that support it by checking for the capability in the vm SKU.
**Test plan for issue:**
- Added unit tests for determining network type.
- Created a cluster and verified Azure Portal shows Accelerated Networking is enabled for masters/workers.  Did NOT test this with vmsizes that don't support accelerated networking as there are not any available in the dev sub.
- Upgraded a cluster from from 4.11.16 -> 4.11.21 to validate network connectivity to Gateway.
- Created an image stream and deployed an app using the image stream.
> enable accelerated networking

- pkg/installer/generateconfig.go
[ARO-1476](https://issues.redhat.com//browse/ARO-1476)
This change allows the user to pass in the NetworkType for 4.10. We found this while working on setting the default to OVNKubernetes in 4.11.
Related #16
> [release-4.10] ARO-1476: Allow user to set NetworkType

- pkg/api/featureflags.go
Removes UserDefinedRouting FeatureFlag.  It doesn't look like its actually used but this change will keep this repo in sync with ARO-RP.
> remove udr feature flag

- pkg/installer/deployresources_resources.go
*CHANGE NEEDS TO BE TESTED* One line change to grab install config values to set bootstrapVM install size instead of hardcoded value.
> Setting bootstrap vm size to requested install size

- Dockerfile.aro
Fixes the failing **ci/prow/images** check (see below).  This check is currently failing in all other open PRs (https://github.com/openshift/ARO-Installer/pull/22, https://github.com/openshift/ARO-Installer/pull/30).
```
[1/2] STEP 8/8: RUN make aro
go generate ./...
fatal: detected dubious ownership in repository at '/go/src/github.com/openshift/ARO-Installer' 
```
Root cause is a new security feature introduced in Git 2.35.2.  See this blog for context:
https://github.blog/2022-04-18-highlights-from-git-2-36/#stricter-repository-ownership-checks
Other repositories under the OpenShift organization are applying similar workarounds.
OpenShift Console, for example: https://github.com/openshift/console/pull/12828#issuecomment-1553244113
> Dockerfile.aro: Apply safe.directory configuration to repo

- docs/publish-rhcos-image.md
- hack/rhcos-sas/rhcos-sas.go
hack/rhcos-sas needs to be moved from ARO-RP
to ARO-Installer, as it depends on the OpenShift installer.
the doc is also moved, docs/publish-rhcos-image.md
Jira: https://issues.redhat.com/browse/ARO-2525
> Move rhcos-sas.go script to ARO-Installer

- pkg/env/prod.go
p.Environment().KeyVaultScope should accommodate both prod (MSI) and dev (certificate) authentication paths
> Correct scope for KV MSI

- Dockerfile.aro
TIL where to find available tags: [ARO.Build.Images repository in Azure DevOps](https://msazure.visualstudio.com/AzureRedHatOpenShift/_git/ARO.Build.Images)
> Fix the ubi8/go-toolset image tag

- pkg/util/steps/condition.go
- pkg/util/steps/runner_test.go
(mirror of changes made in Azure/ARO-RP#3005)
Does not fix [ARO-1558](https://issues.redhat.com/browse/ARO-1558), but provides further clarity in log messages when the below issue is encountered
This change will wrap all `ErrWaitTimeout` errors (`"timed out waiting for the condition"`) returned within our steps runner. 
The `wait.PollImmediateUntil()` function used within our Condition checker returns an `ErrWaitTimeout` of its own when the condition is not met within the specified timeout, leading internal errors within the conditions that match `ErrWaitTimeout` to appear identical to conditions that legitimately time out. 
A unit test was added to the runner tests to handle this specific case. 
No.
- The wrapped error will still match `ErrWaitTimeout` (e.g. `errors.Is(err, …
> Wrap Timeout errors within Condition steps

- Dockerfile.aro
[ARO-3198: Release 4.12 image](https://issues.redhat.com/browse/ARO-3198)
This PR is to update the version of go-toolset to the version we mirrored in the Isolated ACR (1.19.10)
https://msazure.visualstudio.com/AzureRedHatOpenShift/_git/ARO.Build.Images/pullrequest/8465849
> Updating go-toolset from 1.19 to 1.19.10

- pkg/util/version/const.go
Part of [ARO-6628](https://issues.redhat.com/browse/ARO-6628)
Updates images for MDM/MDSD/Fluentbit utilized by the RP infra and by clusters to the latest supported versions. 
Details about specific coordinates included in the story card linked above. 
N/A 
- Hold this PR until we validate the changes against a running cluster in the linked ARO-RP PR. 
- Change needs to be cherrypicked to all active release branches
> MDM/MDSD/Fluentbit Image Bumps

- docs/upstream-differences.md
- hack/installtest/create.sh
- hack/installtest/delete.sh
- hack/installtest/test.sh
This PR migrates upstream-differences.md from [ARO-RP](https://github.com/Azure/ARO-RP/blob/master/docs/upstream-differences.md) to here.
Also it adds a script that needed when I do https://issues.redhat.com/browse/ARO-6198.
Once we have the install in prod regions, we need to install some clusters to make sure that there is no increase in installer failure rate.
This hack script can help to test multiple installations at one time in a region.
See https://github.com/Azure/ARO-RP/pull/3565 why I created the PR here.
Once the PR is merged, I'll create a PR to change upstream-differences.md to link to this doc.
> Migrate upstream-differences.md

- pkg/util/version/const.go
Companion PR to https://github.com/Azure/ARO-RP/pull/3612
Fixes [ARO-7837](https://issues.redhat.com/browse/ARO-7837)
Updates our coordinates for Geneva MDM/MDSD images to explicitly use the distroless variant of these images.
- Validated manually by performing a cluster install in a full-service environment, and SSHing to the bootstrap node to ensure the `mdsd.service` was healthy
This change should be cherry-picked to all active/in-progress release branches.
> Update coordinates for MDM/MDSD images

- pkg/api/openshiftcluster.go
- pkg/installer/generateconfig.go
If a PlatformWorkloadIdentityProfile is specified, then set the credentials mode to "Manual" and if not, set the credentials mode to "Passthrough".
NB this also updates the ServicePrincipalProfile to be a pointer
> ARO-6408 populate the CredentialsMode in the install config

- pkg/installer/deployresources.go
- pkg/installer/deployresources_test.go
Fixes no Jira yet
Explicitly converts zones passed in for the master VMs to ARM to string. This defends us from any ARM behavioral changes causing these values to render as integers (which are not supported for this field)
No
Tests performed above should validate that this results in a valid ARM template.
> Explicitly convert zone definition for master VMs to string

- go.mod
- go.sum
- vendor/modules.txt
bumping installer-aro.
installer-aro is updated because of OWNER change. https://github.com/openshift/installer-aro/pull/30
> [4.14] bump installer-aro

- pkg/installer/aromanifests.go
- pkg/installer/custominstallconfig.go
- pkg/installer/generateconfig.go
Fixes (https://issues.redhat.com/browse/ARO-4518)
- Read manifests from `/manifests` folder created by hive when triggering the installer pod. Manifests are passed from ARO-RP - https://github.com/Azure/ARO-RP/pull/3841 
- Persist all the found manifests to the ARO Cluster graph
- Handle the Azure credentials in install-config based on the type of cluster, miwi vs non-miwi
No.
Please suggest if there's any documentation that needs updating.
- For non-miwi clusters, tested the the cluster creation flow.
- Custom Manifests creation is tested successfully in combination with the ARO-RP PR:- https://github.com/Azure/ARO-RP/pull/3841
> ARO-4518 read custom manifests from hive created volume to persist in cluster graph 

- pkg/installer/install.go
Increase the wait for "bootstrap complete" to 60 minutes.
We've observed a number of ARO cluster install failures where the cluster eventually had a "complete" bootstrap CM present on the APIserver very shortly after the existing 30minute timeout was hit, resulting in "failed" cluster installs for otherwise-healthy clusters.
> Increase bootstrapConfigMapReady condition check timeout to 60 minutes

- hack/installtest/run.go
This PR implements the cluster install tests in go. This enables us to run the install tests across multiple regions while limiting concurrency and saving the output of each cluster install run in a separate log file.
Internally, we just call the `create.sh` and `delete.sh` script a lot of times.
Usage:
```sh
go run ./run.go -h                                                          
Usage of /tmp/go-build639354173/b001/exe/run:
-concurrency int
Maximum number of parallel cluster creations/deletions. <= 0 means unlimited parallelity
-create
weather or not clusters should be created. (default true)
-delete
Weather or not clusters should be deleted.
-num int
number of clusters created/deleted per region (default 6)
-regions string
comman separated list of regions in which to run the tests …
```
> [ARO-9863] Rewrite installtests in go for better concurrency

- pkg/installer/aromanifests.go
- pkg/installer/custominstallconfig.go
- pkg/installer/generateconfig.go
Manual cherry-pick of #166 to handle the module name change between release-4.14 and main/release-4.15
> [release-4.14] ARO-4518 read custom manifests from hive created volume to persist in cluster graph 

- pkg/env/env.go
- pkg/env/prod.go
- pkg/installer/generateconfig.go
- pkg/util/pem/pem.go
- pkg/util/pem/pem_test.go
Manual cherry-pick of #189 to release-4.14, due to module name changes to this repository between 4.14 and 4.15 we cannot automatically cherry-pick this change.
> [release-4.14] Pass the first party service principal certificate to install-config.yaml for MIWI clusters

- hack/validate-imports/validate-imports.go
- pkg/installer/custominstallconfig.go
Append all custom "AROManifests" to the clusterversion's "overrides" list - this will ensure that CVO will not attempt to put down resources we define in custom manifests. 
This implementation duplicates the functionality performed by the upstream installer's CVOIgnore asset for the upstream Manifests assets, though just for our custom AROManifests asset: https://github.com/openshift/installer/blob/release-4.14/pkg/asset/ignition/bootstrap/cvoignore.go
/cherrypick release-4.15 release-4.14
> Add appendFilesToCvoOverrides step to inject AROManifests into CVO Overrides

- go.mod
- go.sum
- vendor/modules.txt
Fix for P0 (runc is only used for 4.13 and 4.12 branch)
JIRA ticket : [ARO-11237](https://issues.redhat.com/browse/ARO-11237)
I didn't succeed to test it locally yet.
> ARO-11237 - Updating runc version

- pkg/cluster/graph/manager.go
- pkg/installer/deployresources.go
- pkg/installer/deployresources_resources.go
- pkg/util/azureclient/azuresdk/azblob/blobs.go
- pkg/util/mocks/graph/graph.go
Fixes https://issues.redhat.com/browse/ARO-9712 in combination with ARO-RP PR:- https://github.com/Azure/ARO-RP/pull/3894
For MIWI:
- Since the storage accounts Cluster will have the shared access keys disabled, the ListAccountSAS won't work, so instead of Account SAS, we need UserDelegatedSAS token to pull the ignition blob from the Cluster Storage Account
[x] Test the flow of cluster install such that the Shared Access Keys are disabled.
[x] Test the flow of cluster install such that the Cluster Service Principal Cluster are created correctly.
No
- For non-MIWI cluster there's no functionality change
- For MIWI cluster the flow has been tested by reversing the usesWorkloadIdentity function. The whole flow can be tested once the feature is tested.
/cherrypick release-4.15 release-4.14
> For miwi use user delegated sas to allow bootstrap node to pull the ignition

- pkg/installer/deployresources_resources.go
Fixes [ARO-11606](https://issues.redhat.com/browse/ARO-11606)
Updates our deployment for the bootstrap and control plane VMs to use [Azure Managed Boot Diagnostics](https://learn.microsoft.com/en-us/azure/virtual-machines/boot-diagnostics#enable-managed-boot-diagnostics), by removing the property for a custom storage account. This will cause these VMs to use an Azure-managed SA that is invisible to the cluster's subscription. 
No
- The ARO-RP E2E [test](https://github.com/Azure/ARO-RP/blob/master/test/e2e/adminapi_serialconsole.go) for serial console log functionality will confirm that it is working after a new version of installer-aro-wrapper is deployed in a production region. 
/cherrypick release-4.15 release-4.14 release-4.13 release-4.12
> Use managed boot diagnostics for bootstrap and master VMs

- data.go
- hack/validate-imports/validate-imports.go
- pkg/installer/data.go
Embed the installer's data/data directory in the binary and substitute it in the installer library where it is expected. This is to work around the fact that the upstream installer does not have the autogenerated data/assets_vfsdata.go file checked in to the repo, so it does not show up in the build.
Since the installer-aro fork _does_ have data/assets_vfsdata.go but does not export the data/data directory, embed the whole data directory and don't substitute it in if data/data does not exist.  So this should have no effect at the moment, but will do the right thing as soon as `github.com/openshift/installer/data/data` is imported from upstream.
> ARO-12457: Embed installer data in the binary

- Makefile
- pkg/installer/custominstallconfig.go
Compile with the altinfra tag, and use a local copy of the target list the same as the one in the installer-aro fork of the installer.
This ensures that when we switch to the upstream installer library, no terraform dependencies will be compiled in to the binary.
> ARO-12466: Avoid terraform dependency in installer

- pkg/installer/custominstallconfig_test.go
- pkg/installer/init.go
Setting the installer invoker to ARO by updating the manifest config map.
> ARO-12467: Set the invoker to ARO

- pkg/data/manifests/manifests_asset.go
- pkg/data/manifests/opt/openshift/manifests/aro-imageregistry.yaml.template
- pkg/data/manifests/opt/openshift/manifests/aro-ingress-namespace.yaml
- pkg/data/manifests/opt/openshift/manifests/aro-ingress-service.yaml.template
- pkg/data/manifests/opt/openshift/manifests/aro-worker-registries.yaml.template
- pkg/installer/custominstallconfig.go
Adding ARO template file manifests from the ARO fork to the wrapper
to generate them locally.
> ARO-12469: Added template manifest files to ignition

- data.go
- pkg/data/bootstrap/util.go
- pkg/data/manifests/manifests_asset.go
- pkg/data/mdsd/mdsd_files.go
- pkg/installer/custominstallconfig.go
- pkg/installer/custominstallconfig_test.go
- pkg/installer/data.go
- pkg/installer/dnsmasq/dnsmasq.go
- pkg/installer/dnsmasq/dnsmasq_config.go
- pkg/installer/dnsmasq/dnsmasq_restart.go
- pkg/installer/dnsmasq/scripts.go
- pkg/installer/etchost/etchost_assets.go
- pkg/installer/etchost/etchosts.go
- pkg/installer/init.go
- pkg/installer/mdsd/mdsd_config.go
- pkg/installer/regenerate_mcs_certs.go
- pkg/installer/storage_files_testdata.go
- pkg/installer/systemd_files_testdata.go
Replacing the api-int URL in the master pointer ignition with the api-int IP. With this change also updating the machine-config-server certs (located in the bootstrap ignition) to allow masters to pull ignition using the api-int IP.
> ARO-11341: Update Master Pointer Ignition

- pkg/util/version/const.go
Companion PR to https://github.com/Azure/ARO-RP/pull/4038
Which issue this PR addresses:
Fixes [ARO-12456](https://issues.redhat.com/browse/ARO-12456)
What this PR does / why we need it:
Updates our coordinates for Geneva MDM/MDSD images to explicitly use the distroless variant of these images.
/cherrypick release-4.14 release-4.13 release-4.12
> updating mdm mdsd images

- pkg/installer/custominstallconfig.go
- pkg/installer/custominstallconfig_test.go
- pkg/installer/storage_files_testdata.go
Adding a few files into the manifest that were added in the ARO fork 
and missing here.
Adding master and user data secret and removing the DNS
config settings that the installer sets.
Commits referred:
https://github.com/openshift/installer-aro/commit/a6f7ca0485f399efb2e7a90d7e8d2aada288213d
https://github.com/hawkowl/ARO-Installer/commit/95a830f1cf0da2a0164dee7d46c9edc8d4676184
> ARO-11341: Add extra files to manifest

- pkg/proxy/dialer.go
This is left over from when the code was split from the RP.
> Remove the ability to run from a checkout as we no longer do this

- pkg/installer/custominstallconfig.go
I forgot to push this up, oops. This uses the IgnitionConfigs target directly, instead of copying it.
> [4.17] Use the IgnitionConfigs directly

- cmd/aro/create.go
- pkg/installer/custominstallconfig.go
- pkg/installer/custominstallconfig_test.go
- pkg/installer/generateconfig.go
This change reduces the number of manifests that the wrapper generates, as we only care about the ignition ones.
This also has the change to remove a conditional in the Installer.
> [4.16] Reduce duplication of manifest generation and remove unneccessary manifests

- pkg/installer/dnsmasq/scripts/aro-dnsmasq-pre.sh.gotmpl
- pkg/installer/dnsmasq/scripts/dnsmasq.service.gotmpl
- pkg/installer/storage_files_testdata.go
- pkg/installer/systemd_files_testdata.go
Fixes [ARO-15180](https://issues.redhat.com//browse/ARO-15180)
Changes synced from https://github.com/Azure/ARO-RP/pull/4100
We've been overwriting `/etc/resolv.conf`. NetworkManager owns this file and if NetworkManager needs to refresh it we will lose our changes. Instead, create a NetworkManager drop-in `/etc/NetworkManager/conf.d/dns-servers.conf` with the node's IP.
No, but the change needs to be socialized amongst ARO SRE since it affects how nameservers are managed.
Testing has been done with an extant UDR+bad dns cluster to ensure there are no external DNS dependencies. Nodes boot and scale correctly.
> Refactor aro-dnsmasq-pre.sh to not overwrite /etc/resolv.conf

- pkg/installer/dnsmasq/scripts/dnsmasq.conf.gotmpl
- pkg/installer/etchost/etchosts.go
- pkg/installer/storage_files_testdata.go
Fixes [ARO-2799](https://issues.redhat.com//browse/ARO-2799) and [ARO-15424](https://issues.redhat.com//browse/ARO-15424)
Companion PR to https://github.com/Azure/ARO-RP/pull/4135
Implementation of ADR: https://docs.google.com/document/d/1nA1udF8RbJdpFgW3sezlEQGPMgqEQAZ7zvbCu18Zr5Q/
I also slipped in a small tweak to the etchosts template since my editor kept wanting to delete the trailing space from storage_files_testdata.go
> dnsmasq.conf: remove strict-order and add dns-forward-max

- pkg/installer/custominstallconfig.go
Context explained in code comment. Will fix 4.16 and 4.17 MIWI installs.
I validated the changes by testing 4.16 and 4.17 MIWI + CSP installs in local dev.
> Create `/output/manifests` directory for Hive install manager

- pkg/installer/deployresources.go
- pkg/installer/deployresources_test.go
- pkg/installer/generateconfig.go
- pkg/installer/generateconfig_test.go
https://issues.redhat.com/browse/ARO-17219
This supports 4 AZs in a general no-op to how we do it right now, as well as potentially squashing some install failure bugs that might be due to picking SKUs available in only 2 AZs for workers and preventing things with taints from installing, maybe.
> [ARO-17219, 4.16] Support 4 AZs

- pkg/installer/generateconfig.go
Unfortunately we still require this hack to perform installs in the region. 
/cherrypick release-4.17 release-4.16 release-4.15 release-4.14
> Force control plane and workers to be non-zonal in centraluseuap 

- pkg/util/version/const.go
Fixes https://issues.redhat.com/browse/ARO-15991
- This PR bumps the MDM & MDSD image versions
- This is needed to be compliant to Microsoft policies and avoid any POAMS
Test results added in attached JIRA ticket
NA
Tested with live production cluster and on INT. Receiving expected logs and metrics on Geneva
> Made changes to point to the latest MDM and MDSD images

- pkg/util/version/const.go
Fixes https://issues.redhat.com/browse/ARO-15991
- This PR bumps the MDM & MDSD image versions
- This is needed to be compliant to Microsoft policies and avoid any POAMS
Test results added in attached JIRA ticket
NA
Tested with live production cluster and on INT. Receiving expected logs and metrics on Geneva
> Feature/ARO-15991 image changes 4.14

- pkg/util/version/const.go
Fixes https://issues.redhat.com/browse/ARO-15991
- This PR bumps the MDM & MDSD image versions
- This is needed to be compliant to Microsoft policies and avoid any POAMS
Test results added in attached JIRA ticket
NA
Tested with live production cluster and on INT. Receiving expected logs and metrics on Geneva
> Feature/ARO-15991 image changes 4.15

- pkg/installer/generateconfig.go
- pkg/installer/generateconfig_test.go
Part 2 of [ARO-17219](https://issues.redhat.com//browse/ARO-17219)
> [ARO-17219, 4.16] Don't use expanded AZs by default
