- pkg/installer/generateconfig.go
Fixes https://issues.redhat.com/browse/ARO-2025
This PR fixes cluster installation failures when a disk encryption set is not defined.  The call to ParseResourceID fails in the default case, i.e. when user encryption keys aren't provided.
Test plan:  With a full RP service in dev I deployed the updated image and installed clusters with and without a disk encryption set.
> add check for disk encryption set id

- pkg/installer/generateconfig.go
[ARO-1476](https://issues.redhat.com//browse/ARO-1476)
To verify this PR we need to install new ARO cluster and verify NetworkType is OVNKubernetes.
> ARO-1476: Default to OVNKubernetes

- pkg/installer/condition.go
Don't bail out on bootstrap config map ready polling blips, because the control plane might go down for a moment while it updates
> [ARO-2964] Fix control plane blips causing installation failures when the bootstrap readiness is being polled

- pkg/util/azureclient/environments.go
Added missing `SendCertificateChain: true` argument to pkg/util/azureclient/environments
> Add SendCertificateChain

- OWNERS
Updating Owners for ARO-Installer
> Updating ARO-Installer owners 

- OWNERS
We're not active in this repo so we don't want to be pinged for reviews :)
> Remove sd-arch from OWNERS

- OWNERS
Add Dominic to OWNERS. (Welcome to the team!) 🎉
> Add Dominic Finn to OWNERS

- pkg/util/version/const.go
the same fix as this: https://github.com/Azure/ARO-RP/pull/3517/files
> fix mdsd version

- OWNERS
> [4.12] Update owners

- go.mod
- go.sum
- vendor/github.com/openshift/installer/pkg/aro/aroign/etchosts.go
- vendor/github.com/openshift/installer/pkg/asset/ignition/bootstrap/common.go
- vendor/github.com/openshift/installer/pkg/asset/machines/master.go
- vendor/github.com/openshift/installer/pkg/asset/machines/worker.go
- vendor/modules.txt
https://issues.redhat.com/browse/ARO-9569
Tests:
* New 4.14 clusters can be created
* Smoke tests and E2E pass in a new cluster
> [4.14] Updating installer-aro dependency for Ignition /etc/hosts bugfix

- pkg/util/version/const.go
For [ARO-5049](https://issues.redhat.com/browse/ARO-5049)
Update MDM, MDSD image coordinates.
> Update MDSD, MDM image coordinates

- pkg/env/env.go
- pkg/env/prod.go
- pkg/installer/generateconfig.go
- pkg/util/pem/pem.go
- pkg/util/pem/pem_test.go
Manual cherry-pick of https://github.com/openshift/installer-aro-wrapper/pull/189 to release-4.15
> [release-4.15] Pass the first party service principal certificate to install-config.yaml for MIWI clusters

- pkg/api/openshiftcluster.go
- pkg/api/openshiftcluster_test.go
- pkg/installer/generateconfig.go
>  [release-4.14] function to check if a cluster is workload identity or service principal 

- pkg/installer/custominstallconfig_test.go
- pkg/installer/storage_files_testdata.go
- pkg/installer/systemd_files_testdata.go
Adding the unit tests to check the bootstrap ignition files 
for ARO files and their contents
> ARO-12445: Added unit test to check and verify ignition files

- pkg/installer/custominstallconfig.go
- pkg/installer/dnsmasq/dnsmasq.go
- pkg/installer/dnsmasq/dnsmasq_config.go
- pkg/installer/dnsmasq/dnsmasq_restart.go
- pkg/installer/dnsmasq/scripts.go
- pkg/installer/dnsmasq/scripts/99-dnsmasq-restart.gotmpl
- pkg/installer/dnsmasq/scripts/aro-dnsmasq-pre.sh.gotmpl
- pkg/installer/dnsmasq/scripts/dnsmasq.conf.gotmpl
- pkg/installer/dnsmasq/scripts/dnsmasq.service.gotmpl
Adding all the required files for the dnsmasq functionality.
> ARO-8391: Add dnsmasq config to ignition

- hack/validate-imports/allowed-import-names.yaml
- pkg/data/bootstrap/util.go
- pkg/data/mdsd/etc/fluentbit/journal.conf
- pkg/data/mdsd/etc/mdsd.d/mdsd.env.template
- pkg/data/mdsd/etc/mdsd.d/secret/mdsdcert.pem.template
- pkg/data/mdsd/etc/sysconfig/fluentbit.template
- pkg/data/mdsd/etc/sysconfig/mdsd.template
- pkg/data/mdsd/mdsd_files.go
- pkg/data/mdsd/systemd/units/fluentbit.service
- pkg/data/mdsd/systemd/units/mdsd.service
- pkg/installer/custominstallconfig.go
- pkg/installer/custominstallconfig_test.go
- pkg/installer/mdsd/mdsd_config.go
Generating the files needed for mdsd work using the code in
the wrapper that was taken from the ARO fork and adding 
to ignition.
> ARO-8392: Added mdsd config to ignition

- pkg/data/bootstrap/util.go
- pkg/installer/custominstallconfig.go
- pkg/installer/dnsmasq/dnsmasq_config.go
- pkg/installer/etchost/etchost_assets.go
- pkg/installer/etchost/etchost_config.go
- pkg/installer/etchost/etchosts.go
Adding the code to generate etchost files locally for ignition.
> ARO-12469: Added etchost files from the ARO fork 

- pkg/installer/custominstallconfig.go
- pkg/installer/custominstallconfig_test.go
Amending the ignition host of the worker config to the API
int IP.
> ARO-11341:  Add api int host ip to worker

- go.mod
- hack/rhcos-sas/rhcos-sas.go
> [ARO-13770] Update rhcos-sas to use azidext

- pkg/util/azureclient/environments.go
Fixes https://issues.redhat.com/browse/ARO-14563
- FF fails to use govcloud resourcemanagerendpoint, instead defaults to public cloud.
- PR provides the value for AROEnvironment to use the correct cloud.
[] Test in local
[] Test in e2e
[] FF prod E2e
None
Release and Test
/cherrypick release-4.16 release-4.15 release-4.14
> ARO-14563 add cloud value for AROEnvironment

- Dockerfile.aro
- go.mod
Trying to debug the error during pipeline build.
> ARO-14882: Debug Release 4.16

- pkg/util/version/const.go
Fixes https://issues.redhat.com/browse/ARO-15991
- This PR bumps the MDM & MDSD image versions
- This is needed to be compliant to Microsoft policies and avoid any POAMS
Test results added in attached JIRA ticket
NA
Tested with live production cluster and on INT. Receiving expected logs and metrics on Geneva
> Made changes to point to the latest MDM and MDSD images

- pkg/installer/generateconfig.go
Fixes https://issues.redhat.com/browse/ARO-20321
> [ARO-20321] Don't check for availability zones in bad regions (like centraluseuap)
